import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const b=await chromium.launch({channel:'chrome'});const context=await b.newContext();const p=await context.newPage();
const url=process.env.QA_URL||'http://127.0.0.1:4174/';
await p.addInitScript(()=>{window.__audioInstances=[];const Original=window.Audio;window.Audio=class extends Original{constructor(...args){super(...args);window.__audioInstances.push(this)}}});
await p.goto(url);assert.equal(await p.evaluate(()=>window.__audioInstances.filter(a=>!a.paused).length),0);
await p.locator('.sound').click();await p.waitForFunction(()=>window.__audioInstances.some(a=>a.duration>140&&a.currentTime>0));
const duration=await p.evaluate(()=>window.__audioInstances.at(-1).duration);assert.ok(duration>=143&&duration<=145);
await p.getByRole('button',{name:'Switch to Tiếng Việt'}).click();await p.locator('#systems').scrollIntoViewIfNeeded();
assert.equal(await p.evaluate(()=>window.__audioInstances.filter(a=>!a.paused).length),1);
await p.evaluate(()=>{window.__audioInstances.at(-1).currentTime=window.__audioInstances.at(-1).duration-.4});await p.waitForTimeout(1600);assert.ok(await p.evaluate(()=>window.__audioInstances.at(-1).currentTime<3));
await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))});assert.equal(await p.evaluate(()=>window.__audioInstances.filter(a=>!a.paused).length),0);
await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'))});await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>window.__audioInstances.filter(a=>!a.paused).length),1);
await p.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await p.locator('.sound').click();assert.equal(await p.evaluate(()=>window.__audioInstances.filter(a=>!a.paused).length),0);
await fs.writeFile('reports/audio-qa.json',JSON.stringify({duration,noAutoplay:true,singleInstanceAfterLanguageAndNavigation:true,loopBoundarySeekTest:true,visibilityHandlerPauseResume:true,mute:true,limitation:'Visibility event simulated; no claim of physical mobile speaker audibility or a full-duration listening test.'},null,2));await b.close();console.log('Audio acceptance passed');
